COPERNICUS_VARIABLE_CHOICES = [
    ('Popular', [
        ('10m_u_component_of_wind', '10m u-component of wind'),
        ('10m_v_component_of_wind', '10m v-component of wind'),
        ('2m_dewpoint_temperature', '2m dewpoint temperature'),
        ('2m_temperature', '2m temperature'),
        ('mean_sea_level_pressure', 'Mean sea level pressure'),
        ('mean_wave_direction', 'Mean wave direction'),
        ('mean_wave_period', 'Mean wave period'),
        ('sea_surface_temperature', 'Sea surface temperature'),
        ('significant_height_of_combined_wind_waves_and_swell', 'Significant height of combined wind waves and swell'),
        ('surface_pressure', 'Surface pressure'),
        ('total_precipitation', 'Total precipitation'),
    ]),
    ('Temperature and pressure', [
        ('ice_temperature_layer_1', 'Ice temperature layer 1'),
        ('ice_temperature_layer_2', 'Ice temperature layer 2'),
        ('ice_temperature_layer_3', 'Ice temperature layer 3'),
        ('ice_temperature_layer_4', 'Ice temperature layer 4'),
        ('maximum_2m_temperature_since_previous_post_processing', 'Maximum 2m temperature since previous post-processing'),
        ('minimum_2m_temperature_since_previous_post_processing', 'Minimum 2m temperature since previous post-processing'),
        ('skin_temperature', 'Skin temperature'),
    ]),
    ('Wind', [
        ('100m_u_component_of_wind', '100m u-component of wind'),
        ('100m_v_component_of_wind', '100m v-component of wind'),
        ('10m_u_component_of_neutral_wind', '10m u-component of neutral wind'),
        ('10m_v_component_of_neutral_wind', '10m v-component of neutral wind'),
        ('10m_wind_gust_since_previous_post_processing', '10m wind gust since previous post-processing'),
        ('instantaneous_10m_wind_gust', 'Instantaneous 10m wind gust'),
    ]),
    ('Radiation and heat', [
        ('clear_sky_direct_solar_radiation_at_surface', 'Clear-sky direct solar radiation at surface'),
        ('downward_uv_radiation_at_the_surface', 'Downward UV radiation at the surface'),
        ('surface_latent_heat_flux', 'Surface latent heat flux'),
        ('surface_net_solar_radiation', 'Surface net solar radiation'),
        ('surface_net_thermal_radiation', 'Surface net thermal radiation'),
        ('surface_sensible_heat_flux', 'Surface sensible heat flux'),
        ('toa_incident_solar_radiation', 'TOA incident solar radiation'),
        ('top_net_solar_radiation', 'Top net solar radiation'),
        ('top_net_thermal_radiation', 'Top net thermal radiation'),
    ]),
    ('Clouds', [
        ('cloud_base_height', 'Cloud base height'),
        ('high_cloud_cover', 'High cloud cover'),
        ('low_cloud_cover', 'Low cloud cover'),
        ('medium_cloud_cover', 'Medium cloud cover'),
        ('total_cloud_cover', 'Total cloud cover'),
        ('total_column_cloud_ice_water', 'Total column cloud ice water'),
        ('total_column_cloud_liquid_water', 'Total column cloud liquid water'),
    ]),
    ('Precipitation and rain', [
        ('convective_precipitation', 'Convective precipitation'),
        ('convective_rain_rate', 'Convective rain rate'),
        ('large_scale_precipitation', 'Large scale precipitation'),
        ('precipitation_type', 'Precipitation type'),
        ('total_column_rain_water', 'Total column rain water'),
    ]),
    ('Snow', [
        ('convective_snowfall', 'Convective snowfall'),
        ('snow_albedo', 'Snow albedo'),
        ('snow_density', 'Snow density'),
        ('snow_depth', 'Snow depth'),
        ('snow_evaporation', 'Snow evaporation'),
        ('snowfall', 'Snowfall'),
        ('snowmelt', 'Snowmelt'),
    ]),
    ('Soil', [
        ('soil_temperature_level_1', 'Soil temperature level 1'),
        ('soil_temperature_level_2', 'Soil temperature level 2'),
        ('soil_temperature_level_3', 'Soil temperature level 3'),
        ('soil_temperature_level_4', 'Soil temperature level 4'),
        ('volumetric_soil_water_layer_1', 'Volumetric soil water layer 1'),
        ('volumetric_soil_water_layer_2', 'Volumetric soil water layer 2'),
        ('volumetric_soil_water_layer_3', 'Volumetric soil water layer 3'),
        ('volumetric_soil_water_layer_4', 'Volumetric soil water layer 4'),
    ]),
    ('Ocean waves', [
        ('peak_wave_period', 'Peak wave period'),
        ('significant_height_of_total_swell', 'Significant height of total swell'),
        ('significant_height_of_wind_waves', 'Significant height of wind waves'),
    ]),
    ('Other', [
        ('boundary_layer_height', 'Boundary layer height'),
        ('charnock', 'Charnock'),
        ('friction_velocity', 'Friction velocity'),
        ('geopotential', 'Geopotential'),
        ('land_sea_mask', 'Land-sea mask'),
        ('sea_ice_cover', 'Sea-ice cover'),
        ('total_column_ozone', 'Total column ozone'),
        ('total_column_water_vapour', 'Total column water vapour'),
    ])
]